### ISSUE TITLE
音频转码到amr失败，请确认你的ffmpeg可以处理此转换

### ISSUE THREAD

**Issue by ziiqq** [yhArcadia/YunzaiJsPlugins#1]
V2js的问题，ffmpeg已经配置好环境变量，但是还是报错
[2022-09-06T23:07:34.566] [MARK] [私聊][七()] 可莉说你好:genshinSpeak
【语音合成】
【音色】: 可莉
【内容】: 你好
[2022-09-06T23:07:34.924] [MARK] ApiRejection { code: -60, message: '音频转码到amr失败，请确认你的ffmpeg可以处理此转换' }

$ ffmpeg -version
ffmpeg version 2022-08-31-git-319e8a49b5-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      57. 34.100 / 57. 34.100
libavcodec     59. 42.103 / 59. 42.103
libavformat    59. 30.100 / 59. 30.100
libavdevice    59.  8.101 / 59.  8.101
libavfilter     8. 46.103 /  8. 46.103
libswscale      6.  8.104 /  6.  8.104
libswresample   4.  9.100 /  4.  9.100
libpostproc    56.  7.100 / 56.  7.100

**Comment by ziiqq** [comment]
已解决

**Comment by TerryW-tx** [comment]
> 已解决

请问是如何解决的呢，谢谢！

**Comment by ziiqq** [comment]
> > 已解决
> 
> 请问是如何解决的呢，谢谢！
严格来说我也不知道具体是怎么解决的...我是官网下的7z包然后配置的环境变量，如果ffmpeg配置好，环境变量也配置好但是js还是报错，那就只能试一下更新重启yunzai...我还试了npm install ffmpeg但是这个感觉应该没什么用
